feat  (logger): Add loki compatibility.
overextended/ox_lib pull request #115
Opened 2022-10-05 00:20 UTC by IdrisDose

Instead of using DataDog, due to pricing and other limitations I like to use Grafana Loki, I've added a compatibility patch for that within the logger import.

I had to do a hacky trick with the timestamp as Loki expects a nanosecond timestamp.

2022-10-08 13:25 UTC, thelindat commented
I still want to do some additional logging changes in the future, but for now resolve the conflicts and I can merge.

2022-10-08 13:56 UTC, thelindat requested changes

2022-10-08 13:56 UTC, thelindat commented on imports/logger/server.lua
> +        local timestamp = tostring(os.time(os.date("*t")) ) .. "000000000"
```lua
('%s000000000'):format(os.time(os.date('*t')))
```
micro

2022-10-09 12:06 UTC, IdrisDose commented on imports/logger/server.lua
> +		})
Yeah it's accepts arrays but in a weird way, will do though

2022-10-09 12:11 UTC, IdrisDose commented on imports/logger/server.lua
> +        end
Would you be okay if I made it an optional parameter? easier for log traversal and filtering if it's sent as a json kvp.

The intention behind this was to allow for both 'Player X given Player Y item Z' as well as `{player='X', target = 'Y', item='Z'}`

2022-10-09 14:04 UTC, IdrisDose commented
Requires Testing before merging.

2022-10-10 00:44 UTC, thelindat commented
> Requires Testing before merging.

Hope you mean you'll be testing it, because I'd like to merge this before a new tag but need to setup grafana and whatnot.
Requires documentation changes as well https://github.com/overextended/overextended.github.io/blob/main/docs/ox_lib/Logger/Server.md

2022-10-10 00:57 UTC, IdrisDose commented
Yeah, I'll be testing it after work today.

2022-10-10 06:54 UTC, IdrisDose commented
Tested and works

2022-10-10 07:02 UTC, thelindat commented
Either two separate pages or use tabs, don't mind. I need to do a full guide on datadog anyway.

2022-10-10 07:03 UTC, merged