fix(web/menu): Combine initial select and first render checks
overextended/ox_lib pull request #172
Opened 2022-12-13 01:31 UTC by jag3dagster

* Combining these checks should fix an issue of having to toggle a checkbox multiple times before it is recognized as being toggled

2022-12-13 22:28 UTC, LukeWasTakenn requested changes
Seems to be triggering onSideScroll on open if the first item in the menu is a side scroll button 😭

2022-12-13 23:07 UTC, jag3dagster commented
Oh right... because both onSelect and onSideScroll would get called for the same item on initial render... Back to the drawing board

2022-12-14 14:57 UTC, LukeWasTakenn requested changes

2022-12-14 14:57 UTC, LukeWasTakenn commented on web/src/features/menu/list/index.tsx
> +    if (firstRenderRef.current) firstRenderRef.current = false
Issue with this is that if the first button is a normal button the `onSelect` event won't fire.

2022-12-14 15:10 UTC, LukeWasTakenn commented
@jag3dagster I've pushed a possible fix so it *should* hopefully work as intended now, would appreciate it if you could test it as well.

2022-12-14 17:11 UTC, jag3dagster commented
So if I'm seeing that change correctly, you only want onSelect to fire on initial load/render?

2022-12-14 17:13 UTC, LukeWasTakenn commented
> So if I'm seeing that change correctly, you only want onSelect to fire on initial load/render?

Yeah that's the idea, it's also how it worked so far 🤷

2022-12-14 17:19 UTC, jag3dagster commented
Gotcha. I misunderstood them when I made that addition to onSelect. This should work as described now, I'll double-check when I get to my desk.

2022-12-14 17:58 UTC, jag3dagster commented
Yeup, just verified, this is working as described @LukeWasTakenn . I'm only seeing onSelected called on initial load / render and see everything else working on menu interactions.

2022-12-14 17:59 UTC, LukeWasTakenn commented
nice, thanks for the PR 👍

2022-12-14 17:59 UTC, merged