feat(web/context): mouse enter and mouse leave events
overextended/ox_lib pull request #218
Opened 2023-02-06 16:00 UTC by masonschafercodes

does what it says. Adds two new things to context options for capturing mouse enter and mouse leave events on the button.

2023-02-07 11:40 UTC, LukeWasTakenn requested changes

2023-02-07 11:40 UTC, LukeWasTakenn commented on package/client/resource/interface/context.ts
> +  onLeave?: (args: any) => void;
These should probably be one function, something like:

```lua
onHover = function(entered)
    if entered then
        -- Do stuff when mouse enters
    else
        -- Do stuff when mouse leaves
    end
end

2023-02-07 11:40 UTC, LukeWasTakenn commented on resource/interface/client/context.lua
> +    end
This conversion can go into it's own function I think, to avoid repeating it 3 times.

2023-02-07 11:40 UTC, LukeWasTakenn commented on web/src/features/menu/context/components/ContextButton.tsx
> +
These can go inline, same with `clickContext`.

2023-02-07 14:58 UTC, masonschafercodes commented
Let me change these things and test out to see if the leave event is triggered onClose.

2023-02-07 15:51 UTC, masonschafercodes commented
Seems that I get the same result when testing the it for this as well. If `ESC` is pressed there is no callback made for the `onMouseLeave`. Is this something we should simulate by triggering the callback when the Modal closes (only if the `onHover` options is even present)?

2023-02-07 16:03 UTC, masonschafercodes commented
could be good to keep the currently hovered button and then `onClose` we check to see if there is an active hovered button and if so then we trigger the callback for it, then clear the currently hovered state.

2023-02-07 17:30 UTC, masonschafercodes commented
That commit should cover the following cases:
- run the `onHover` function when the user clicks on an option that has an `onHover` attached to it
- run the `onHover` function when the user was hovering over a option with a `onHover` and closes the context menu

2023-02-08 09:05 UTC, LukeWasTakenn approved these changes

2023-02-08 09:05 UTC, merged