Add clearAllRadialItems
overextended/ox_lib pull request #272
Opened 2023-03-13 18:39 UTC by Mkeefeus

I used this for our conversion from qb-radialmenu to clear the menu then only add a "call for help" option or similar. Figured it could be useful in other niche situations

2023-03-15 20:07 UTC, LukeWasTakenn requested changes
Could you also make a PR to the docs for this function?

2023-03-15 20:07 UTC, LukeWasTakenn commented on resource/interface/client/radial.lua
> +function lib.clearAllRadialItems()
I think `clearRadialItems` would be a bit better than `clearAllRadialItems`

2023-03-15 20:07 UTC, LukeWasTakenn commented on resource/interface/client/radial.lua
> +    end
Why not do a check for `not currentRadial` as well and update the menu instead of closing it?

2023-03-15 23:30 UTC, Mkeefeus commented
Requested updates made and the PR for docs is open

2023-03-16 08:25 UTC, LukeWasTakenn approved these changes

2023-03-16 08:26 UTC, merged