Changes to input fields
overextended/ox_lib pull request #372
Opened 2023-07-17 18:19 UTC by daZepelin

- fix: added missing disabled prop to checkbox
  - checkbox disabled prop used to not work

- feat: added precision prop for number input
  - without this, the number from input was always returned as integer, while in some cases float might be useful

2023-07-21 11:45 UTC, LukeWasTakenn requested changes

2023-07-21 11:45 UTC, LukeWasTakenn commented on web/src/features/dialog/components/fields/number.tsx
>        disabled={props.row.disabled}
The step prop is missing but is defined in the typings.

2023-07-25 11:56 UTC, LukeWasTakenn requested changes
Why remove the step prop from the typings instead of passing it to the actual component?

2023-07-25 13:10 UTC, daZepelin commented
> Why remove the step prop from the typings instead of passing it to the actual component?

As I understand, the project is aiming to make it as simplistic as possible for usage and I am not entirely sure if this is a neccesary feature, as barely any people use the arrow buttons to increase or decrease the values. But I can surely add that if you think it will be needed, as myself I added it just by accident by testing

2023-07-25 13:24 UTC, LukeWasTakenn commented
> > Why remove the step prop from the typings instead of passing it to the actual component?
> 
> As I understand, the project is aiming to make it as simplistic as possible for usage and I am not entirely sure if this is a neccesary feature, as barely any people use the arrow buttons to increase or decrease the values. But I can surely add that if you think it will be needed, as myself I added it just by accident when testing

Sure I guess that makes sense, remove the step prop from the debug dialog and then this can be merged.

2023-07-26 04:58 UTC, masonschafercodes commented
> barely any people use the arrow buttons to increase or decrease the values

In my opinion this is the wrong way to approach simplicity, simplicity has never meant removing a feature rather making that feature approachable for the end user. Just cause **you** haven't seen people use the step feature, doesn't mean people don't use it.

2023-07-26 05:15 UTC, jag3dagster commented
> implicity has never meant removing a feature rather making that feature approachable for the end user

This is the core of an never ending debate. On one hand, you have the user's perspective of preference or accessibility, on the other hand you have the overhead of code maintenance and supporting various ways to accomplish the same task. Ultimately it is up to the maintainer of a code base to decide which side of 'simplicity' they want to lean into as it is on them in the long run to support things as a project continues to move forward.

2023-07-26 14:41 UTC, daZepelin commented
> > barely any people use the arrow buttons to increase or decrease the values
> 
> In my opinion this is the wrong way to approach simplicity, simplicity has never meant removing a feature rather making that feature approachable for the end user. Just cause **you** haven't seen people use the step feature, doesn't mean people don't use it.

This feature was never removed, it has never been added, I accidentally added the step prop when testing as I though it will make the input fields support the float numbers.
I do understand that some might use it, but don't see it as necessary as it supporting float numbers.
The mantine library (the one used for the inputs) has like 30 - 40 props on each input field type and I hornestly do not think that all of them should be implemented in ox_lib and as I saw lots of them not being implemented I'd choose not to add any unnecessary ones.

2023-07-27 09:43 UTC, LukeWasTakenn approved these changes

2023-07-27 09:44 UTC, merged