Fixing and Adding new properties to the vehicleProperties/client.lua
overextended/ox_lib pull request #396
Opened 2023-08-09 13:19 UTC by luxu-gg

Fixed incorrect usage of the `ClearVehicleCustomPrimaryColour()` function on the secondary color.

Added new properties
- paint1 
- paint2 

These 2 functions (get and set) were missing custom paint properties.

The following FiveM natives only work if there is a "RGB coating" applied to the vehicle
```lua
SetVehicleModColor_1()
SetVehicleModColor_2()
```

This "coating" I am referring to is applied when using 
```lua
SetVehicleCustomPrimaryColour()
SetVehicleCustomSecondaryColour()
```
and they can be removed by using
```lua
ClearVehicleCustomPrimaryColour()
ClearVehicleCustomSecondaryColour()
```

I hope this clarifies some doubts around these messy natives.

2023-08-09 13:24 UTC, luxu-gg commented
Here's a good test of these new paint properties in action

Good car for this test: `nero`

```lua
RegisterCommand('testpaint', function()
      local veh = GetVehiclePedIsIn(PlayerPedId(), false)
      SetVehicleModKit(veh, 0)
      local props = lib.getVehicleProperties(veh)
      props.color1 = { 20, 255, 20 }
      props.color2 = { 255, 20, 20 }
      props.paint1 = 5 -- set paint to chrome
      props.paint2 = 5 -- set paint to chrome
      lib.setVehicleProperties(veh, props)
end, false)

RegisterCommand('resetpaint', function()
      local veh = GetVehiclePedIsIn(PlayerPedId(), false)
      local props = lib.getVehicleProperties(veh)

      props.color1 = 2
      props.color2 = 0
      props.paint1 = 3
      props.paint2 = 3
      lib.setVehicleProperties(veh, props)
end, false)
```

2023-08-12 23:48 UTC, thelindat requested changes

2023-08-12 23:48 UTC, thelindat commented on resource/vehicleProperties/client.lua
> +        local paint2, p1_color2 = GetVehicleModColor_2(vehicle)
Unused variables with snake_case?

2023-08-12 23:48 UTC, thelindat commented on resource/vehicleProperties/client.lua
> +            paint2 = paint2,
These are 0 for none right? Not much point storing in that case.

2023-08-12 23:48 UTC, thelindat commented on resource/vehicleProperties/client.lua
> +            if type(props.paint1) == 'number' then SetVehicleModColor_1(vehicle, props.paint1, colorPrimary, pearlescentColor) end
Should just be `if props.paint1`? Does pearlescentColor conflict with (the unused) p1_pearlescentColor?

2023-08-12 23:48 UTC, thelindat commented on resource/vehicleProperties/client.lua
> +            if type(props.paint2) == 'number' then SetVehicleModColor_2(vehicle, props.paint2, colorSecondary) end
Again should just check if it's defined?

2023-08-12 23:48 UTC, thelindat commented on resource/vehicleProperties/client.lua
> +---@field paint2? number
TS types.

2023-08-12 23:51 UTC, thelindat commented on resource/vehicleProperties/client.lua
> +        local paint2, p1_color2 = GetVehicleModColor_2(vehicle)
Also should be `modColor1`, `modColor2`. Possibly need to store as an array if the other variables aren't trash?

2023-08-15 00:37 UTC, merged