Update menu.lua
overextended/ox_lib pull request #445
Opened 2023-10-22 21:39 UTC by Zaps6000

Fixing a nil error for a native not on redm

2023-10-24 15:15 UTC, LukeWasTakenn reviewed
Is there not a similar or equivalent native for RedM?

2023-10-24 23:59 UTC, Zaps6000 commented
> Is there not a similar or equivalent native for RedM?

If this is I couldnt find it I Just know that every time you open a menu it returns nil

2023-10-25 00:23 UTC, Zaps6000 commented
I looked again and am pretty sure there isn't one unless it isn't on the docs

2023-10-28 16:05 UTC, LukeWasTakenn requested changes
Fix the weird formatting issues and then it should be good to to be merged.

2023-10-28 16:05 UTC, LukeWasTakenn commented on resource/interface/client/menu.lua
> +
Don't remove the space

2023-10-28 16:05 UTC, LukeWasTakenn commented on resource/interface/client/menu.lua
> +                    HudWeaponWheelIgnoreSelection() -- Not a REDM native
This should be indented

2023-10-28 16:05 UTC, LukeWasTakenn commented on resource/interface/client/menu.lua
> +                        end
This should not be indented

2023-10-28 19:03 UTC, Zaps6000 commented
> Fix the weird formatting issues and then it should be good to to be merged.

should be good

2023-11-03 14:33 UTC, LukeWasTakenn approved these changes

2023-11-03 14:34 UTC, merged