feat(client/notification): add support for native audio sounds
overextended/ox_lib pull request #455
Opened 2023-11-15 17:41 UTC by Ehbw

As requested by luke, #362 and #441. Adds support for an additional table value to be passed in to play sounds 

Example:
```lua
lib.notify({
   title = 'Info', 
   description = 'my text.',
   position = 'top',
   duration = 5000, 
   sound = {--[[bank = "BANKNAME",]] name = "Near_Miss_Counter_Reset", set = "GTAO_FM_Events_Soundset"}, 
   type = 'success'
})
```

2023-11-15 19:29 UTC, LukeWasTakenn requested changes
Perhaps make it a custom sound like what was done for ox_doorlock [here](https://github.com/overextended/ox_doorlock/commit/5debf40916370a35d71aa8cbab1d333dea50c6b3).

So people have a basis to go off of when they want to implement theirs.

Can take the same `audio` folder structure as ox_doorlock, as for what the actual notification sound itself should be I'm not too sure, I think something like the new notifications sounds for steam's new UI sound quite good 🤔

2023-11-15 19:29 UTC, LukeWasTakenn commented on imports/requestAudioBank/client.lua
> +return lib.requestAudioBank
I don't think we really need a lib wrapper for a single native, and definitely not a whole new module 🤷

2023-11-15 20:29 UTC, Ehbw commented
> Perhaps make it a custom sound like what was done for ox_doorlock [here](https://github.com/overextended/ox_doorlock/commit/5debf40916370a35d71aa8cbab1d333dea50c6b3).
> 
> So people have a basis to go off of when they want to implement theirs.

Should I make it so if no sound is provided it will use the custom sound by default (toggleable by convar like you mentioned in discord)? So people have the ability to use base game sounds (like in the example I posted)

2023-11-15 21:03 UTC, LukeWasTakenn commented
> > Perhaps make it a custom sound like what was done for ox_doorlock [here](https://github.com/overextended/ox_doorlock/commit/5debf40916370a35d71aa8cbab1d333dea50c6b3).
> > So people have a basis to go off of when they want to implement theirs.
> 
> Should I make it so if no sound is provided it will use the custom sound by default (toggleable by convar like you mentioned in discord)? So people have the ability to use base game sounds (like in the example I posted)

I think rather than using a convar then having people constantly ask how to change the default sound, it's just better to have people constantly define the sound if they want to use sounds on notifications.

People who know what they are doing will just easily edit the source code and set a default.

2023-11-18 11:18 UTC, LukeWasTakenn approved these changes
Should be good to merge, can you make a PR for the docs on the `lib-update` branch?

2023-12-17 17:20 UTC, Ehbw commented
> Should be good to merge, can you make a PR for the docs on the `lib-update` branch?

Bit late, but done https://github.com/overextended/overextended.github.io/pull/164

2024-01-15 01:12 UTC, thelindat commented
I'm not going to accept this until we have a settings menu so people can toggle sounds (and other future features).

2024-04-01 08:47 UTC, thelindat requested changes
Please add a slider option for notification_audio to the settings menu added with 
https://github.com/overextended/ox_lib/commit/2d4e56d828a51578c3380e1ca35a7afa64d319ee#diff-cc6b1038f3003216b59df7605e18b125928666b987a1fe027fd97b9f7b704c17

2024-04-01 08:47 UTC, thelindat commented on imports/requestAudioBank/client.lua
> +function lib.requestAudioBank(audioBank, timeout)
@Ehbw Can I get you to update `requestAudioBank` to be in-line with the changes in https://github.com/overextended/ox_lib/commit/0f0c7a659124659b038dd2e0be9f004b76c7ce10

Also needs a TypeScript counterpart.

2024-04-01 08:47 UTC, thelindat commented on resource/interface/client/notify.lua
> +local enableSound = GetConvar('ox:enableSound', 'true') == 'true'
Use `GetConvarInt` and  `1`.

2024-04-01 08:47 UTC, thelindat commented on resource/interface/client/notify.lua
> +    end
Just minor complaints about formatting - line breaks before/after if statements.

2024-04-03 03:48 UTC, merged