TS support for addCommand
overextended/ox_lib pull request #482
Opened 2024-01-11 17:00 UTC by ESK0

I would like to mention in advance that I am completely new to TS and thanks to the transition of ox_core to TS I got the motivation to dive more into this and learn the language.

I looked at what is available in ox_lib for TS and addCommand came to me as one of the few must have functions that ox_lib currently lacks..

I am more than sure that this PR has flaws and I would appreciate any feedback and change requests

Tested with:
```
import { addCommand } from '@overextended/ox_lib/server'

addCommand('tscommand', (source: number, args: any, raw: string) => {
    console.log(`player ${source} executed comand (${raw})`)
}, {help: 'TypeScript addCommand', params: [{name: 'target', paramType: 'playerId', help: 'playerId or "me"', optional: true}], restricted: ['group.typescript', 'group.typescript2'] } )
```

2024-01-12 14:13 UTC, LukeWasTakenn requested changes
A lot of uses of `let` when most of these variables can be `const`, should always use `const` unless you really *must* use `let`.

Also please use Prettier with the config that's in the root of the `package` dir and reformat your code with it.

2024-01-12 14:13 UTC, LukeWasTakenn commented on package/server/resource/addCommand/index.ts
> +        let value: any
there's no reason not to type this when we are assigning it later and expect it to be of certain type

2024-01-13 15:32 UTC, ESK0 commented
Thanks for review! Ill try to solve all requests later today or tomorrow

2024-01-14 15:31 UTC, ESK0 commented
Should be all good now... fingers crossed

2024-01-15 01:10 UTC, merged