fix(progress/client): sync props with statebags
overextended/ox_lib pull request #515
Opened 2024-03-11 23:09 UTC by Andyyy7666

Changed props spawning from networked on client to just spawn non networked on clients using statebag

2024-03-14 19:15 UTC, Andyyy7666 commented
@thelindat tested with multiple players, no issues found.

2024-03-15 17:39 UTC, thelindat requested changes

2024-03-15 17:39 UTC, thelindat commented on resource/interface/client/progress.lua
> +        playerState:set("lib:progressProps", nil, true)
I use `'` for strings, not `"`.

2024-03-15 17:39 UTC, thelindat commented on resource/interface/client/progress.lua
> +AddStateBagChangeHandler("lib:progressProps", nil, function(bagName, key, value, reserved, replicated)
Wrong string style again.

2024-03-15 18:55 UTC, FjamZoo commented
After clearing the props in `deleteProgressProps` you should probably wipe the cached data aswell, as we don't want to store props that no longer exsist

2024-03-15 20:42 UTC, Andyyy7666 commented
@thelindat done!

2024-03-18 07:51 UTC, thelindat requested changes

2024-03-18 07:51 UTC, thelindat commented on resource/interface/client/progress.lua
> +AddStateBagChangeHandler("lib:progressProps", nil, function(bagName, key, value, reserved, replicated)
> "lib:progressProps"
Not resolved.

2024-03-18 07:51 UTC, thelindat commented on resource/interface/client/progress.lua
> +    playerProps = nil
This does basically nothing. You should be assigning `createdProps[id] = nil` rather than the variable referencing it.

2024-03-19 07:01 UTC, merged